### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BrancoX5** [ChuckTheSheep/pz-shops#7]
Hello, Chuck! Thanks for this awesome mod!
While on a server, when a shop is set a player can pick up the object that the shop was set. It would be cool if when an object becomes a shop, it can't be picked up. Also, if possible, it would be cool if we can interact with shops that are set inside safezones that have the loot setting off. Because if a shop is inside a protected safezone, we can't interact.

**Comment by ChuckTheSheep** [comment]
175e8a4d16e5ffa20178ef6bcece093e041c98f4
